services:
  backend:
    command: npm run dev
    build:
      context: ./backend        # look inside backend folder
      dockerfile: ../Dockerfile # optional: if your Dockerfile is in root
    volumes:
      - ./backend:/app          # mount local backend code into container /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000

    depends_on:
      - db
    restart: unless-stopped

  frontend:
    command: npm run dev -- --host
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped

  db:
    image: postgres:16-bookworm
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
