services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      - PORT=3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    name: app-net
