services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
    ports:
      - "5432:5432"

  node-backend:
    build: ./backend
    depends_on: [ postgres ]
    ports:
      - "3000:3000"
    environment:
      PG_HOST: postgres
      PG_USER: postgres
      PG_DATABASE: postgres
      PG_PASSWORD: postgres
      PG_PORT: 5432

  frontend:
    build: ./frontend
    depends_on: [ node-backend ]
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host

volumes:
  dbdata: