name: Backend Tests

on:
  push:
    branches: [ "cb" ]
  pull_request:
    branches: [ "cb" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend deps
        working-directory: backend
        run: npm ci

      - name: Run tests
        working-directory: backend
        env:
          NODE_ENV: test
        run: npm test
